plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.compose)
  alias(libs.plugins.google.devtools.ksp)
  alias(libs.plugins.roborazzi)
  alias(libs.plugins.secrets)
  alias(libs.plugins.kotlin.serialization)
}

// FCM: بيتفعّل بس لما google-services.json يكون موجود — CI والأجهزة المحلية
// من غير الملف بتبني عادي، وأول ما الملف يجي Firebase بيتفعّل لوحده.
// (apply خارج بلوك plugins{} عشان الشرط مش مسموح جواه)
if (projectDir.resolve("google-services.json").exists()) {
  apply(plugin = "com.google.gms.google-services")
}

android {
  namespace = "com.example"
  compileSdk = 36

  defaultConfig {
    applicationId = "com.aistudio.zad.wrtqvx"
    minSdk = 24
    targetSdk = 35
    // كانت ثابتة على 1 / "1.0" من أول التطبيق — يعني مستحيل تفرّق نسخة عن نسخة من
    // شاشة "حول التطبيق"، وكانت بتزوّد لخبطة "هو ده البيلد الجديد ولا القديم؟".
    versionCode = 2
    versionName = "1.1"

    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

    // Secrets are automatically injected into BuildConfig by the secrets-gradle-plugin
  }

  signingConfigs {
    // debug كان بيستخدم ~/.android/debug.keystore الافتراضي — الملف ده **مش موجود على
    // سيرفر CI**، فبيتولّد جديد عشوائي في كل بيلد. النتيجة: كل APK موقّع بمفتاح مختلف
    // (اتأكد بالمقارنة: بيلد 04ee86e شهادته 0bec552a…، بيلد 998e229 شهادته 1f9ccc34…)،
    // وأندرويد بيرفض يثبّت APK فوق تطبيق متثبّت لو التوقيع اتغيّر → "التطبيق غير مثبت"
    // → الجهاز يفضل شايل النسخة القديمة مهما اتبنى كود جديد. ده كان سبب "بفتح التطبيق
    // بلاقيه زي الشهر اللي فات" رغم إن الكود فعلاً جوه الـAPK.
    //
    // keystore ثابت متسجّل في الريبو. ده **مش سر**: مفاتيح الديباج معروفة بالتعريف
    // (كلمة السر القياسية `android`)، ومابتوقّعش أي حاجة بتتنشر على المتجر — النشر
    // بيستخدم signingConfigs("release") تحت باللي جاي من متغيرات البيئة.
    getByName("debug") {
      storeFile = file("${rootDir}/zad-debug.keystore")
      storePassword = "android"
      keyAlias = "androiddebugkey"
      keyPassword = "android"
    }
    create("release") {
      val keystorePath = System.getenv("KEYSTORE_PATH") ?: "${rootDir}/my-upload-key.jks"
      storeFile = file(keystorePath)
      storePassword = System.getenv("STORE_PASSWORD")
      keyAlias = "upload"
      keyPassword = System.getenv("KEY_PASSWORD")
    }
  }

  buildTypes {
    release {
      // R8: APK أصغر + كود مش مقروء. القواعد في proguard-rules.pro بتخلي
      // Supabase/gson/Room/SQLCipher شغالين (reflection-heavy libraries).
      isMinifyEnabled = true
      isShrinkResources = true
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
      signingConfig = signingConfigs.getByName("release")
    }
    debug {
      // Use default debug keystore generated by Android
    }
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    // java.time.* is used throughout (ZadCentralBrain, workers, etc.) but only
    // ships natively from API 26 — minSdk is 24, so this backports it to API 24-25.
    isCoreLibraryDesugaringEnabled = true
  }
  buildFeatures {
    compose = true
    buildConfig = true
  }
  testOptions { unitTests { isIncludeAndroidResources = true } }
  lint {
    baseline = file("lint-baseline.xml")
    abortOnError = false
    checkReleaseBuilds = false
  }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
  compilerOptions {
    jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    freeCompilerArgs.addAll("-opt-in=androidx.compose.material3.ExperimentalMaterial3Api")
  }
}

// Configure the Secrets Gradle Plugin to use .env and .env.example files
// to match the convention used in Web projects.
secrets {
  propertiesFileName = ".env"
  defaultPropertiesFileName = ".env.example"
}




// Some unused dependencies are commented out below instead of being removed.
// This makes it easy to add them back in the future if needed.
dependencies {
    implementation("androidx.appcompat:appcompat:1.6.1")
  implementation(platform(libs.androidx.compose.bom))

  // تشفير قاعدة البيانات المحلية — بيانات مالية ماينفعش تنام plain
  implementation("net.zetetic:android-database-sqlcipher:4.5.4")
  implementation("androidx.sqlite:sqlite-ktx:2.4.0")

  // implementation(libs.accompanist.permissions)
  implementation(libs.androidx.activity.compose)
  implementation("androidx.camera:camera-camera2:1.4.1")
  implementation("androidx.camera:camera-core:1.4.1")
  implementation("androidx.camera:camera-lifecycle:1.4.1")
  implementation("androidx.camera:camera-view:1.4.1")
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.datastore.preferences)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  implementation(libs.androidx.navigation.compose)
  implementation(libs.androidx.room.ktx)
  implementation(libs.androidx.room.runtime)
  implementation(libs.coil.compose)
  implementation(libs.lottie.compose)
  implementation(libs.converter.moshi)

  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.logging.interceptor)
  implementation(libs.moshi.kotlin)
  implementation(libs.okhttp)
  implementation(libs.play.services.location)
  implementation(libs.retrofit)
  // FCM — الوعي اللحظي للأيدجنت. google-services plugin بيتفعّل لو الملف موجود
  // (app/google-services.json)، وFirebase BOM بيمدّ كلاس الماسنجر.
  implementation(platform(libs.firebase.bom))
  implementation("com.google.firebase:firebase-messaging")
  implementation("com.google.android.gms:play-services-ads:23.3.0")
  implementation("com.android.billingclient:billing-ktx:7.1.1")

  // Gemini & Supabase
  // Removed generativeai to fix Ktor 3 conflicts
  val supabaseVersion = "3.0.3"
  implementation("io.github.jan-tennert.supabase:postgrest-kt:$supabaseVersion")
  implementation("io.github.jan-tennert.supabase:auth-kt:$supabaseVersion")
  implementation("io.github.jan-tennert.supabase:realtime-kt:$supabaseVersion")
  implementation("io.github.jan-tennert.supabase:functions-kt:$supabaseVersion")
  implementation("io.github.jan-tennert.supabase:storage-kt:$supabaseVersion")
  implementation("io.ktor:ktor-client-okhttp:3.0.1")
  implementation("androidx.compose.runtime:runtime-livedata:1.7.5")
  implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
  implementation("androidx.work:work-runtime-ktx:2.9.0")
  testImplementation(libs.androidx.compose.ui.test.junit4)
  testImplementation(libs.androidx.core)
  testImplementation(libs.androidx.junit)
  testImplementation(libs.junit)
  testImplementation(libs.kotlinx.coroutines.test)
  testImplementation(libs.robolectric)
  testImplementation(libs.roborazzi)
  testImplementation(libs.roborazzi.compose)
  testImplementation(libs.roborazzi.junit.rule)
  testImplementation("io.mockk:mockk:1.13.10")
  androidTestImplementation("io.mockk:mockk-android:1.13.10")
  androidTestImplementation(platform(libs.androidx.compose.bom))
  androidTestImplementation(libs.androidx.compose.ui.test.junit4)
  androidTestImplementation(libs.androidx.espresso.core)
  androidTestImplementation(libs.androidx.junit)
  androidTestImplementation(libs.androidx.runner)
  debugImplementation(libs.androidx.compose.ui.test.manifest)
  debugImplementation(libs.androidx.compose.ui.tooling)
  "ksp"(libs.androidx.room.compiler)
  "ksp"(libs.moshi.kotlin.codegen)
  implementation("com.google.zxing:core:3.5.3")
  coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}
